version: 0.2
variable:
  
phases:
  install: 
    runtime-version:
      nodejs: 16
    commands:
      - cd react-app
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build
artifacts:
  base-directory: react-app/build
  files:
    - '**/*'
  name: ReactAppBuild